<a href="https://colab.research.google.com/github/chocozzang/My_Python_Practice/blob/main/%EC%9E%91%EC%97%85_2%EC%9C%A0%ED%98%95_%EC%95%99%EC%83%81%EB%B8%94_%EB%B6%80%EC%8A%A4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/breast-cancer-wisconsin.csv', encoding='utf-8')

data = data.loc[data['bare_nucleoli'].str.isnumeric()]

x = data[data.columns[1:10]]
y = data[['class']]

In [6]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify = y, random_state = 42)

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(x_train)
x_scaled_train = scaler.transform(x_train)
x_scaled_test  = scaler.transform(x_test)

In [10]:
from sklearn.ensemble import AdaBoostClassifier

model = AdaBoostClassifier(n_estimators = 100, random_state = 0)
model.fit(x_scaled_train, y_train)
pred_train = model.predict(x_scaled_train)
model.score(x_scaled_train, y_train)

1.0

In [12]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train, pred_train)
print("train data confusion matrix \n", cm)

train data confusion matrix 
 [[333   0]
 [  0 179]]


In [14]:
from sklearn.metrics import classification_report

cr = classification_report(y_train, pred_train)
print("train data classification report \n", cr)

train data classification report 
               precision    recall  f1-score   support

           2       1.00      1.00      1.00       333
           4       1.00      1.00      1.00       179

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512



In [11]:
pred_test = model.predict(x_scaled_test)
model.score(x_scaled_test, y_test)

0.9532163742690059

In [15]:
from sklearn.metrics import confusion_matrix

cm2 = confusion_matrix(y_test, pred_test)
print("test data confusion matrix \n", cm2)

test data confusion matrix 
 [[106   5]
 [  3  57]]


In [16]:
from sklearn.metrics import classification_report

cr2 = classification_report(y_test, pred_test)
print("test data classification report \n", cr2)

test data classification report 
               precision    recall  f1-score   support

           2       0.97      0.95      0.96       111
           4       0.92      0.95      0.93        60

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [17]:
from sklearn.ensemble import GradientBoostingClassifier

model2 = GradientBoostingClassifier(n_estimators = 100, learning_rate = 0.1, max_depth = 1, random_state = 0)
model2.fit(x_scaled_train, y_train)
pred_train2 = model2.predict(x_scaled_train)
model2.score(x_scaled_train, y_train)

0.984375

In [18]:
from sklearn.metrics import confusion_matrix

cm3 = confusion_matrix(y_train, pred_train2)
print("train data confusion matrix \n", cm3)

train data confusion matrix 
 [[329   4]
 [  4 175]]


In [19]:
pred_test2 = model2.predict(x_scaled_test)
model2.score(x_scaled_test, y_test)

0.9649122807017544

In [20]:
from sklearn.metrics import pair_confusion_matrix

cm4 = confusion_matrix(y_test, pred_test2)
print("test data confusion matrix \n", cm4)

test data confusion matrix 
 [[106   5]
 [  1  59]]


In [22]:
data2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/house_price.csv', encoding = 'utf-8')

x2 = data2[data2.columns[1:5]]
y2 = data2[['house_value']]

x_train2, x_test2, y_train2, y_test2 = train_test_split(x2, y2, random_state = 42)

scaler2 = MinMaxScaler()
scaler2.fit(x_train2)
x_scaled_train2 = scaler2.transform(x_train2)
x_scaled_test2  = scaler2.transform(x_test2)

In [23]:
from sklearn.ensemble import AdaBoostRegressor

model3 = AdaBoostRegressor(n_estimators = 100, random_state = 0)
model3.fit(x_scaled_train2, y_train2)
pred_train3 = model3.predict(x_scaled_train2)
model3.score(x_scaled_train2, y_train2)

0.4353130085971758

In [24]:
pred_test3 = model3.predict(x_scaled_test2)
model3.score(x_scaled_test2, y_test2)

0.43568387094087124

In [26]:
import numpy as np
from sklearn.metrics import mean_squared_error

MSE_train = mean_squared_error(y_train2, pred_train3)
MSE_test  = mean_squared_error(y_test2,  pred_test3)

print("RMSE TRAIN : ", np.sqrt(MSE_train))
print("RMSE TEST  : ", np.sqrt(MSE_test))

RMSE TRAIN :  71722.42012035428
RMSE TEST  :  71816.41231019037


In [28]:
from sklearn.ensemble import GradientBoostingRegressor

model4 = GradientBoostingRegressor(random_state = 0)
model4.fit(x_scaled_train2, y_train2)
pred_train4 = model4.predict(x_scaled_train2)
model4.score(x_scaled_train2, y_train2)

0.6178724780500952

In [31]:
pred_test4 = model4.predict(x_scaled_test2)
model4.score(x_scaled_test2, y_test2)

0.5974112241813845

In [33]:
MSE_train2 = mean_squared_error(y_train2, pred_train4)
MSE_test2  = mean_squared_error(y_test2, pred_test4)

print("RMSE TRAIN : ", np.sqrt(MSE_train2))
print("RMSE TEST  : ", np.sqrt(MSE_test2))

RMSE TRAIN :  59000.433545962376
RMSE TEST  :  60658.72886338227
